fieldList = '''(
URL TEXT,
GameType TEXT,
Location TEXT,
Date TEXT,
Time TEXT,
WinningTeam TEXT,
Quarter TEXT,
SecLeft TEXT,
AwayTeam TEXT,
AwayPlay TEXT,
AwayScore TEXT,
HomeTeam TEXT,
HomePlay TEXT,
HomeScore TEXT,
Shooter TEXT,
ShotType TEXT,
ShotOutcome TEXT,
ShotDist TEXT,
Assister TEXT,
Blocker TEXT,
FoulType TEXT,
Fouler TEXT,
Fouled TEXT,
Rebounder TEXT,
ReboundType TEXT,
ViolationPlayer TEXT,
ViolationType TEXT,
TimeoutTeam TEXT,
FreeThrowShooter TEXT,
FreeThrowOutcome TEXT,
FreeThrowNum TEXT,
EnterGame TEXT,
LeaveGame TEXT,
TurnoverPlayer TEXT,
TurnoverType TEXT,
TurnoverCause TEXT,
TurnoverCauser TEXT,
JumpballAwayPlayer TEXT,
JumpballHomePlayer TEXT,
JumpballPoss TEXT
)'''

db_table = "PBP"

db.buildTable(tableName=db_table, fieldList=fieldList)
